services:
  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/

  app:
    container_name: student_management_app
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=student_management
      - DB_PORT=5432
      - DB_SSL_MODE=disable
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
    depends_on:
      - db
